### ISSUE TITLE
Combining mark behavior is different from commonmark.js

### ISSUE THREAD

**Issue by notriddle** [jgm/commonmark-hs#114]
This input is composed of the codepoints U+002A U+002E U+002A U+0300 U+002E

```markdown
*.*̀.
```

[pandoc seems to treat the second `*` as surrounded by punctuation on both sides](https://pandoc.org/try/?params=%7B%22text%22%3A%22*%5C%22*%CC%80.%5Cn%22%2C%22to%22%3A%22html5%22%2C%22from%22%3A%22commonmark%22%2C%22standalone%22%3Afalse%2C%22embed-resources%22%3Afalse%2C%22table-of-contents%22%3Afalse%2C%22number-sections%22%3Afalse%2C%22citeproc%22%3Afalse%2C%22html-math-method%22%3A%22plain%22%2C%22wrap%22%3A%22auto%22%2C%22highlight-style%22%3Anull%2C%22files%22%3A%7B%7D%2C%22template%22%3Anull%7D)

[commonmark dingus does not](https://spec.commonmark.org/dingus/?text=*.*%CC%80.)

**Comment by jgm** [comment]
The combining mark is tokenized as
```
Symbol '\768'
```
https://github.com/jgm/commonmark-hs/blob/master/commonmark/src/Commonmark/Inlines.hs#L396-L399
decides if the next token is punctuation by seeing if it's a WordChars token -- because it's a Symbol, this is counted as punctuation.

I'm actually not entirely sure how this *should* be handled.

**Comment by jgm** [comment]
It probably makes sense to tokenize combining accents as WordChars...currently it's only alphanumerics and spaces.
